export type TokenInfo = {
  address: `0x${string}`;
  symbol: string;
  name: string;
  decimals: number;
};
export type PositionData = {
  chainId: number;
  blockNumber: string;
  blockHash: string;
  managerAddress: `0x${string}`;
  tokenId: string;
  owner: `0x${string}`;
  operator: `0x${string}`;
  pool: {
    address: `0x${string}`;
    fee: number;
    tickSpacing: number;
    liquidity: string;
    unlocked: boolean;
    observationIndex: number;
    observationCardinality: number;
    observationCardinalityNext: number;
    feeProtocol: number;
  };
  token0: TokenInfo;
  token1: TokenInfo;
  tickLower: number;
  tickUpper: number;
  tick: number;
  sqrtPriceX96: string;
  liquidity: string;
  amount0: string;
  amount1: string;
  tokensOwed0: string;
  tokensOwed1: string;
  feePreview: { amount0: string; amount1: string; available: boolean };
  state: "IN_RANGE" | "NEAR_BOUNDARY" | "OUT_OF_RANGE";
  priceToken1PerToken0: number;
  lowerPriceToken1PerToken0: number;
  upperPriceToken1PerToken0: number;
};

export type WorkflowPlan = {
  version: number;
  workflowKey: string;
  requestHash: string;
  action: string;
  chainId: number;
  owner: string;
  tokenId: string;
  quoteBlock: string;
  quoteBlockHash: string;
  quoteTimestamp: string;
  expiresAt: string;
  slippageBps: number;
  deadline: string;
  position: PositionData;
  steps: Array<{
    ordinal: number;
    kind: string;
    label: string;
    target: `0x${string}`;
    method: string;
    calldata: `0x${string}`;
    value: string;
    simulated: boolean;
    simulationError?: string;
    gasEstimate?: string;
    requiresFreshPlanAfter?: boolean;
  }>;
  nextPhase: null | Record<string, unknown>;
  expected: { amount0: string; amount1: string; liquidityDelta: string };
  gasEstimate: string;
  maxFeePerGas: string;
  maximumGasCostWei: string;
  liveExecutionEnabled: boolean;
  recovery: string;
};
